spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME:juniordsj@gmail.com}
    password: ${MAIL_PASSWORD:frva trfp ynup jghj}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  datasource:
    url: jdbc:postgresql://localhost:5432/hotel_reservation
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:senha123}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      idle-timeout: 10000
      max-lifetime: 1800000
      connection-timeout: 30000

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: true
        format_sql: true
    open-in-view: true

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    com.hotel.reservation: DEBUG
    org.springframework: INFO

rabbitmq:
  host: localhost
  port: 5672
  username: guest
  password: guest
  virtual-host: /
  connection-timeout: 15000
  requested-heartbeat: 60